### ISSUE TITLE
Tried to access a JS module before the React instance was fully set up.

### ISSUE THREAD

**Issue by mojjominion** [mojjominion/barcode-broadcast-receiver#6]
```
java.lang.IllegalStateException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.
    at com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:159)
    at expo.modules.adapters.react.services.EventEmitterModule.emit(EventEmitterModule.java:26)
    at expo.modules.kotlin.events.KEventEmitterWrapper.emit
    at expo.modules.kotlin.events.KModuleEventEmitterWrapper.emit(KModuleEventEmitterWrapper.kt:27)
    at expo.modules.kotlin.modules.Module.sendEvent(Module.kt:30)
    at expo.modules.clipboard.ClipboardModule$ClipboardEventEmitter.listener$lambda-7(ClipboardModule.kt:163)
    at expo.modules.clipboard.ClipboardModule$ClipboardEventEmitter.$r8$lambda$FOcG-I7941H4UsJXOpcE8zMe3jo
    at expo.modules.clipboard.ClipboardModule$ClipboardEventEmitter$$ExternalSyntheticLambda0.onPrimaryClipChanged
    at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:250)
    at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0$ClipboardManager$1(ClipboardManager.java:62)
    at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    ```

**Comment by mojjominion** [comment]
solution is to call `getJsModule` after checking is react context has been initialized 
```
 if (getReactApplicationContext().hasActiveCatalystInstance()) {
      ....
          reactContext.getJSModule(RCTDeviceEventEmitter.class)
     ....
    }
   ```
